apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: notifications
  name: notifications
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notifications
  template:
    metadata:
      labels:
        app: notifications
    spec:
      containers:
      - image: us-east1-docker.pkg.dev/sleep-434401/notifications/production
        name: notifications
        env:
          - name:  PORT
            value: '3000'
          - name:  GOOGLE_OAUTH_CLIENT_ID
            value: 383879160129-q040e86g2d1j0osh7rat2e5icfo28m11.apps.googleusercontent.com
          - name:  SMTP_USER
            value: iurybrasileiromsilva@gmail.com
          - name:  GOOGLE_OAUTH_CLIENT_SECRET
            valueFrom:
              secretKeyRef: 
                name: google
                key: clientSecret
          - name:  GOOGLE_OAUTH_REFRESH_TOKEN
            valueFrom:
              secretKeyRef: 
                name: google
                key: refreshToken
        ports:
          - containerPort: 3000
